# -*- coding: utf-8 -*-
"""Homework2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSHx5DGFBg5gUU-k_ZL_8WuHA3WOIZ3Q
"""

#Problem 1
#use the 'solve' function from the NumPy package in Python to solve the following system of equations:

#2*x1 - 6*x2 - x3 = -38
#-3*x1 - x2 + 7*x3 = -34
#-8*x1 + x2 -2*x3 = -20

#write a python script that define the coefficient matrix and the right-hand side vector.
#use np.linalg.solve() to compute the solution.
#print the solution

import numpy as np

# Define the coefficient matrix (A)
A = np.array([
    [2, -6, -1],
    [-3, -1, 7],
    [-8, 1, -2]
])

# Define the right-hand side vector (b)
b = np.array([-38, -34, -20])

# Solve the system of equations A * x = b
x = np.linalg.solve(A, b)

# Print the solution
print("Solution:")
print(f"x1 = {x[0]:.2f}")
print(f"x2 = {x[1]:.2f}")
print(f"x3 = {x[2]:.2f}")